# Generated by Django 5.2.6 on 2025-10-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="last_refresh",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
