# Generated by Django 5.2.6 on 2025-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_person_last_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="metadata_src",
            field=models.CharField(
                choices=[("t", "tvmaze"), ("m", "moviedb")], default="t", max_length=1
            ),
            preserve_default=False,
        ),
    ]
