# Generated by Django 5.2.8 on 2025-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_person_metadata_src"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tracking_movie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="tracking_movie_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="tracking_tv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="tracking_tv_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
