# Generated by Django 5.2.8 on 2025-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0001_initial"),
        ("people", "0004_person_tracking_movie_person_tracking_movie_started_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tvmaze_id__isnull", False),
                    ("the_moviedb_id__isnull", False),
                    _connector="OR",
                ),
                name="at_least_tvmaze_id_or_the_moviedb_id",
            ),
        ),
    ]
