# Generated by Django 5.2.8 on 2025-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_person_at_least_tvmaze_id_or_the_moviedb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
