# Generated by Django 5.0.6 on 2024-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_collection_movie_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
