# Generated by Django 5.0.6 on 2024-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
