# Generated by Django 5.1.4 on 2024-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movie_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "Rumored"),
                    ("p", "Planned"),
                    ("i", "In Production"),
                    ("p", "Post Production"),
                    ("r", "Released"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
