# Generated by Django 5.1.4 on 2024-12-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_movie_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                (
                    "release_type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Premiere"),
                            (2, "Theatrical (limited)"),
                            (3, "Theatrical"),
                            (4, "Digital"),
                            (5, "Physical"),
                            (6, "TV"),
                        ]
                    ),
                ),
                ("release_date", models.DateTimeField()),
                ("release_lang", models.CharField(blank=True, max_length=2, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
                    ),
                ),
            ],
        ),
    ]
