# Generated by Django 5.1.4 on 2024-12-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_movierelease"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movierelease",
            unique_together={("movie", "release_type")},
        ),
    ]
