# Generated by Django 5.1.4 on 2025-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0009_alter_torrent_torrent_type"),
        ("movie", "0007_alter_movierelease_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="media_server_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="media_server_meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("u", "Upcoming"),
                    ("s", "Searching"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "Ignored"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="torrent",
            field=models.ManyToManyField(related_name="torrent", to="autot.torrent"),
        ),
    ]
