# Generated by Django 5.1.4 on 2025-01-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_movie_media_server_id_movie_media_server_meta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="status",
            new_name="production_state",
        ),
    ]
