# Generated by Django 5.1.4 on 2025-01-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_rename_status_movie_production_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="state",
            new_name="status",
        ),
    ]
