# Generated by Django 5.2 on 2025-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_rename_state_movie_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="production_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "Rumored"),
                    ("p", "Planned"),
                    ("i", "In Production"),
                    ("o", "Post Production"),
                    ("e", "Released"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
