# Generated by Django 5.2.2 on 2025-06-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_alter_movie_production_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieReleaseTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.JSONField(default=[])),
            ],
        ),
    ]
