# Generated by Django 5.2.2 on 2025-06-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_moviereleasetarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereleasetarget",
            name="target",
            field=models.JSONField(default=list),
        ),
    ]
