# Generated by Django 5.2.2 on 2025-06-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_alter_moviereleasetarget_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("n", "None"),
                    ("u", "Upcoming"),
                    ("s", "Searching"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "Ignored"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
