# Generated by Django 5.2.2 on 2025-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0016_alter_autotscheduler_job"),
        ("movie", "0014_alter_movie_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="search_keywords",
            field=models.ManyToManyField(to="autot.searchword"),
        ),
    ]
