# Generated by Django 5.2.2 on 2025-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_movie_search_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="movie_ids",
            field=models.JSONField(default=list),
        ),
    ]
