# Generated by Django 5.2.2 on 2025-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0016_collection_movie_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="tracking",
            field=models.BooleanField(default=False),
        ),
    ]
