# Generated by Django 5.2.2 on 2025-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0017_collection_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
