# Generated by Django 5.2.2 on 2025-06-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0018_targetbitrate"),
        ("movie", "0018_movie_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="target_bitrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="autot.targetbitrate",
            ),
        ),
    ]
