# Generated by Django 5.2.2 on 2025-06-18 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0018_targetbitrate"),
        ("movie", "0019_movie_target_bitrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="target_bitrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="autot.targetbitrate",
            ),
        ),
    ]
