# Generated by Django 5.2.3 on 2025-06-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0020_alter_movie_target_bitrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.collection",
            ),
        ),
    ]
