# Generated by Django 5.2.3 on 2025-06-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0021_alter_movie_collection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="remote_server_id",
            new_name="the_moviedb_id",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="movie_ids",
            new_name="the_moviedb_ids",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="remote_server_id",
            new_name="the_moviedb_id",
        ),
    ]
