# Generated by Django 5.2.4 on 2025-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0022_rename_remote_server_id_collection_the_moviedb_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereleasetarget",
            name="target",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
