# Generated by Django 5.2.4 on 2025-07-16 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0001_initial"),
        ("movie", "0023_alter_moviereleasetarget_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="image_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_collection",
                to="artwork.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_movie",
                to="artwork.artwork",
            ),
        ),
    ]
