# Generated by Django 5.2.6 on 2025-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0024_alter_collection_image_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name=255
            ),
        ),
    ]
