# Generated by Django 5.2.6 on 2025-10-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0025_movie_imdb_id"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="credit",
            field=models.ManyToManyField(to="people.credit"),
        ),
    ]
