# Generated by Django 5.2.8 on 2025-11-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0026_movie_credit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Movie", "verbose_name_plural": "Movies"},
        ),
    ]
