# Generated by Django 5.2.8 on 2025-11-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0027_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movie.collection",
            ),
        ),
    ]
