# Generated by Django 6.0.2 on 2026-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0028_alter_movie_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="search_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
