# Generated by Django 5.0.6 on 2024-06-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchWordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnet", models.TextField(unique=True)),
                (
                    "torrent_type",
                    models.CharField(
                        choices=[("e", "Episode"), ("s", "Season")], max_length=1
                    ),
                ),
                (
                    "torrent_state",
                    models.CharField(
                        choices=[
                            ("u", "undefined"),
                            ("q", "queued"),
                            ("d", "downloading"),
                            ("f", "finished"),
                            ("a", "archived"),
                        ],
                        default="u",
                        max_length=1,
                    ),
                ),
                ("progress", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("i", "Include"), ("e", "Exclude")],
                        default="i",
                        max_length=1,
                    ),
                ),
                ("movie_default", models.BooleanField(default=False)),
                ("tv_default", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="autot.searchwordcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("direction", "category", "word")},
            },
        ),
    ]
