# Generated by Django 5.0.2 on 2024-03-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magnet", models.TextField()),
                ("torrent_type", models.CharField(choices=[("t", "tv")], max_length=1)),
                (
                    "torrent_state",
                    models.CharField(
                        choices=[
                            ("u", "undefined"),
                            ("q", "queued"),
                            ("d", "downloading"),
                            ("f", "finished"),
                            ("a", "archived"),
                        ],
                        default="u",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TVSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("number", models.IntegerField()),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TVEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "media_server_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("u", "Upcoming"),
                            ("s", "Searching"),
                            ("d", "Downloading"),
                            ("f", "Finished"),
                            ("i", "Ignored"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
                (
                    "torrent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autot.torrent",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autot.tvseason"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("r", "Running"),
                            ("e", "Ended"),
                            ("d", "In Development"),
                            ("t", "To Be Determined"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tvseason",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autot.tvshow"
            ),
        ),
    ]
