# Generated by Django 5.0.6 on 2024-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="remote_server_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvseason",
            name="remote_server_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="remote_server_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
