# Generated by Django 5.0.2 on 2024-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="is_daily",
            field=models.BooleanField(default=False),
        ),
    ]
