# Generated by Django 5.0.6 on 2024-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_state",
            field=models.CharField(
                choices=[
                    ("u", "Undefined"),
                    ("q", "Queued"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                ],
                default="u",
                max_length=1,
            ),
        ),
    ]
