# Generated by Django 5.0.2 on 2024-03-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0002_tvshow_is_daily"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="show_time_zone",
            field=models.CharField(default="UTC", max_length=255),
        ),
    ]
