# Generated by Django 5.1.2 on 2024-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0002_alter_torrent_torrent_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_state",
            field=models.CharField(
                choices=[
                    ("u", "Undefined"),
                    ("q", "Queued"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "ignored"),
                ],
                default="u",
                max_length=1,
            ),
        ),
    ]
