# Generated by Django 5.0.6 on 2024-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0002_tvepisode_remote_server_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchword",
            name="applies_to_movie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="searchword",
            name="applies_to_tv",
            field=models.BooleanField(default=False),
        ),
    ]
