# Generated by Django 5.0.2 on 2024-03-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0003_tvshow_show_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvepisode",
            name="remote_server_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="remote_server_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="remote_server_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
