# Generated by Django 5.0.6 on 2024-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0003_searchword_applies_to_movie_searchword_applies_to_tv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchword",
            old_name="applies_to_tv",
            new_name="tv_default",
        ),
        migrations.RemoveField(
            model_name="searchword",
            name="applies_to_movie",
        ),
        migrations.RemoveField(
            model_name="searchword",
            name="is_default",
        ),
        migrations.AddField(
            model_name="searchword",
            name="movie_default",
            field=models.BooleanField(default=False),
        ),
    ]
