# Generated by Django 5.1.2 on 2024-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0003_alter_torrent_torrent_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutotScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[("tv.tasks.refresh_all_shows", "Refresh All Shows")],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("cron_schedule", models.CharField(max_length=255)),
            ],
        ),
    ]
