# Generated by Django 5.1.3 on 2024-11-09 04:21

import autot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0004_autotscheduler"),
    ]

    operations = [
        migrations.AddField(
            model_name="autotscheduler",
            name="job_id_registered",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="autotscheduler",
            name="cron_schedule",
            field=models.CharField(
                max_length=255, validators=[autot.models.validate_cron]
            ),
        ),
    ]
