# Generated by Django 5.0.2 on 2024-03-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0004_alter_tvepisode_remote_server_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="search_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
