# Generated by Django 5.0.2 on 2024-03-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0005_tvshow_search_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tvseason",
            unique_together={("show", "number")},
        ),
    ]
