# Generated by Django 5.1.3 on 2024-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0005_autotscheduler_job_id_registered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Status"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
