# Generated by Django 5.1.3 on 2024-11-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0007_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
