# Generated by Django 5.1.4 on 2025-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0008_actionlog_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_type",
            field=models.CharField(
                choices=[("e", "Episode"), ("s", "Season"), ("m", "Movie")],
                max_length=1,
            ),
        ),
    ]
