# Generated by Django 5.0.3 on 2024-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0008_tvshow_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchword",
            name="category",
            field=models.CharField(
                choices=[("r", "Resolution"), ("c", "Codec"), ("f", "Free")],
                default="f",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="searchword",
            name="direction",
            field=models.CharField(
                choices=[("i", "Include"), ("e", "Exclude")], default="i", max_length=1
            ),
        ),
    ]
