# Generated by Django 5.1.4 on 2025-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0009_alter_torrent_torrent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="magnet",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="torrent",
            unique_together={("magnet", "torrent_type")},
        ),
    ]
