# Generated by Django 5.0.3 on 2024-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0009_searchword_category_searchword_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="tvseason",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
