# Generated by Django 5.0.3 on 2024-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0010_tvepisode_image_tvseason_image_tvshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_type",
            field=models.CharField(choices=[("e", "tv")], max_length=1),
        ),
    ]
