# Generated by Django 5.1.5 on 2025-02-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0010_alter_torrent_magnet_alter_torrent_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="has_expected_files",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
