# Generated by Django 5.0.3 on 2024-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0011_alter_torrent_torrent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_type",
            field=models.CharField(
                choices=[("e", "Episode"), ("s", "Season")], max_length=1
            ),
        ),
    ]
