# Generated by Django 5.1.7 on 2025-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0011_torrent_has_expected_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_state",
            field=models.CharField(
                choices=[
                    ("u", "Undefined"),
                    ("q", "Queued"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "Ignored"),
                ],
                default="u",
                max_length=1,
            ),
        ),
    ]
