# Generated by Django 5.2 on 2025-05-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0012_alter_torrent_torrent_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autotscheduler",
            name="job_id_registered",
        ),
    ]
