# Generated by Django 5.0.3 on 2024-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0012_alter_torrent_torrent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="progress",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
