# Generated by Django 5.0.3 on 2024-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0013_torrent_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchWordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="searchword",
            name="word",
            field=models.CharField(default="na", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="searchword",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="autot.searchwordcategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchword",
            unique_together={("direction", "category", "word")},
        ),
    ]
