# Generated by Django 5.2 on 2025-05-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0013_remove_autotscheduler_job_id_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Episode Status"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
