# Generated by Django 5.0.6 on 2024-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0014_searchwordcategory_alter_searchword_word_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="image_blur",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvseason",
            name="image_blur",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="image_blur",
            field=models.TextField(blank=True, null=True),
        ),
    ]
