# Generated by Django 5.2.2 on 2025-06-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0015_alter_autotscheduler_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Episode Status"),
                    ("movie.tasks.refresh_all_movies", "Refresh all Movies"),
                    ("movie.tasks.refresh_status", "Refresh Movie Status"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
