# Generated by Django 5.2.2 on 2025-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0016_alter_autotscheduler_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
