# Generated by Django 5.2.2 on 2025-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0017_torrent_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetBitrate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitrate", models.FloatField()),
                ("plusminus", models.PositiveIntegerField()),
                ("movie_default", models.BooleanField(default=False)),
                ("tv_default", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("movie_default", True)),
                        fields=("movie_default",),
                        name="only_one_movie_default",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tv_default", True)),
                        fields=("tv_default",),
                        name="only_one_tv_default",
                    ),
                ],
            },
        ),
    ]
