# Generated by Django 5.2.3 on 2025-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0018_targetbitrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="torrent_type",
            field=models.CharField(
                choices=[
                    ("e", "Episode"),
                    ("s", "Season"),
                    ("w", "Show"),
                    ("m", "Movie"),
                ],
                max_length=1,
            ),
        ),
    ]
