# Generated by Django 5.2.6 on 2025-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0019_alter_torrent_torrent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Episode Status"),
                    ("movie.tasks.refresh_all_movies", "Refresh all Movies"),
                    ("movie.tasks.refresh_status", "Refresh Movie Status"),
                    ("autot.tasks.cleanup", "Cleanup Leftovers"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
