# Generated by Django 5.2.6 on 2025-10-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0020_alter_autotscheduler_job"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchword",
            unique_together={
                ("direction", "category", "word", "movie_default", "tv_default")
            },
        ),
    ]
