# Generated by Django 5.2.6 on 2025-10-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0021_alter_searchword_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchword",
            unique_together=set(),
        ),
    ]
