# Generated by Django 5.2.6 on 2025-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0022_alter_searchword_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Episode Status"),
                    ("movie.tasks.refresh_all_movies", "Refresh all Movies"),
                    ("movie.tasks.refresh_status", "Refresh Movie Status"),
                    ("people.tasks.refresh_people", "Refresh People"),
                    ("autot.tasks.cleanup", "Cleanup Database"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
