# Generated by Django 5.2.8 on 2025-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0023_alter_autotscheduler_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "single_lock",
                    models.PositiveSmallIntegerField(default=1, unique=True),
                ),
                (
                    "movie_archive_format",
                    models.CharField(
                        choices=[
                            ("y", "Year folder"),
                            ("f", "First letter folder"),
                            ("s", "Single folder"),
                        ],
                        default="f",
                        max_length=1,
                    ),
                ),
                (
                    "tv_archive_format",
                    models.CharField(
                        choices=[("s", "Season folder")], default="s", max_length=1
                    ),
                ),
            ],
        ),
    ]
