# Generated by Django 5.2.8 on 2025-11-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0024_appconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfig",
            name="file_archive_operation",
            field=models.CharField(
                choices=[
                    ("m", "Move"),
                    ("c", "Copy"),
                    ("d", "Copy and Delete"),
                    ("l", "Hard link"),
                    ("b", "Copy and Hard"),
                ],
                default="c",
                max_length=1,
            ),
        ),
    ]
