# Generated by Django 5.2.8 on 2025-12-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0026_alter_appconfig_file_archive_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfig",
            name="file_archive_operation",
            field=models.CharField(
                choices=[
                    ("m", "Move"),
                    ("c", "Copy"),
                    ("d", "Copy and Delete"),
                    ("l", "Hard link"),
                ],
                default="c",
                max_length=1,
            ),
        ),
    ]
