# Generated by Django 6.0.2 on 2026-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0027_alter_appconfig_file_archive_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotscheduler",
            name="job",
            field=models.CharField(
                choices=[
                    ("tv.tasks.refresh_all_shows", "Refresh All Shows"),
                    ("tv.tasks.refresh_status", "Refresh Episode Status"),
                    ("movie.tasks.refresh_all_movies", "Refresh all Movies"),
                    ("movie.tasks.refresh_status", "Refresh Movie Status"),
                    ("people.tasks.refresh_people", "Refresh People"),
                    ("autot.tasks.cleanup", "Cleanup Database"),
                    ("autot.tasks.clear_cache", "Clear Redis Cache"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
