# Generated by Django 6.0.2 on 2026-03-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0028_alter_autotscheduler_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="has_tracker_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="torrent",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
