# Generated by Django 5.1.5 on 2025-01-27 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shows_active_filter", models.BooleanField(blank=True, null=True)),
                (
                    "shows_status_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("r", "Running"),
                            ("e", "Ended"),
                            ("d", "In Development"),
                            ("t", "To Be Determined"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
