# Generated by Django 5.2 on 2025-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="movie_status_filter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("u", "Upcoming"),
                    ("s", "Searching"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "Ignored"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="movies_production_filter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "Rumored"),
                    ("p", "Planned"),
                    ("i", "In Production"),
                    ("o", "Post Production"),
                    ("e", "Released"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
