# Generated by Django 5.2.2 on 2025-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_movie_status_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="collection_active_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
