# Generated by Django 5.2.2 on 2025-06-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userprofile_collection_active_filter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="collection_active_filter",
            new_name="collection_tracking_filter",
        ),
    ]
