# Generated by Django 5.2.6 on 2025-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0005_rename_collection_active_filter_userprofile_collection_tracking_filter",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="movies_active_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
