# Generated by Django 5.2.8 on 2025-11-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userprofile_movies_active_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="people_credit_filter",
            field=models.CharField(
                blank=True,
                choices=[("m", "movie"), ("t", "tv")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="people_locked_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="people_movie_tracking_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="people_tv_tracking_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
