# Generated by Django 5.2.8 on 2025-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userprofile_people_credit_filter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_support_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_support_remind_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
