# Generated by Django 5.0.2 on 2024-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0006_alter_tvseason_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrent",
            name="magnet",
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="tvepisode",
            unique_together={("season", "number")},
        ),
    ]
