# Generated by Django 5.0.2 on 2024-03-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0007_alter_torrent_magnet_alter_tvepisode_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
