# Generated by Django 5.0.6 on 2024-05-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="artwork/"),
                ),
                ("image_blur", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
