# Generated by Django 6.0.1 on 2026-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMDBRatings",
            fields=[
                ("tconst", models.CharField(primary_key=True, serialize=False)),
                ("averageRating", models.FloatField()),
                ("numVotes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IMDBSynced",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_synced", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField()),
                ("duration_sec", models.IntegerField()),
                (
                    "archive_type",
                    models.CharField(choices=[("r", "rating")], max_length=1),
                ),
            ],
        ),
    ]
