# Generated by Django 5.0.6 on 2024-06-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artwork", "0001_initial"),
        ("autot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255, unique=True)),
                ("remote_server_url", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "search_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("r", "Running"),
                            ("e", "Ended"),
                            ("d", "In Development"),
                            ("t", "To Be Determined"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("is_daily", models.BooleanField(default=False)),
                ("show_time_zone", models.CharField(default="UTC", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "episode_fallback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_fallback",
                        to="artwork.artwork",
                    ),
                ),
                (
                    "image_show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_show",
                        to="artwork.artwork",
                    ),
                ),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
                (
                    "season_fallback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_fallback",
                        to="artwork.artwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TVSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255, unique=True)),
                ("remote_server_url", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("number", models.IntegerField()),
                (
                    "image_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_season",
                        to="artwork.artwork",
                    ),
                ),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tv.tvshow"
                    ),
                ),
            ],
            options={
                "unique_together": {("show", "number")},
            },
        ),
        migrations.CreateModel(
            name="TVEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_server_id", models.CharField(max_length=255, unique=True)),
                ("remote_server_url", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "media_server_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("u", "Upcoming"),
                            ("s", "Searching"),
                            ("d", "Downloading"),
                            ("f", "Finished"),
                            ("i", "Ignored"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "image_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_episode",
                        to="artwork.artwork",
                    ),
                ),
                ("search_keywords", models.ManyToManyField(to="autot.searchword")),
                (
                    "torrent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autot.torrent",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tv.tvseason"
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "number")},
            },
        ),
    ]
