# Generated by Django 5.0.6 on 2024-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="media_server_meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
