# Generated by Django 5.0.6 on 2024-07-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0002_alter_torrent_torrent_state"),
        ("tv", "0002_tvepisode_media_server_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvepisode",
            name="torrent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="torrent_episode",
                to="autot.torrent",
            ),
        ),
    ]
