# Generated by Django 5.1.3 on 2024-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0003_alter_tvepisode_torrent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvepisode",
            name="remote_server_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="remote_server_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="remote_server_id",
            field=models.CharField(max_length=255),
        ),
    ]
