# Generated by Django 5.1.3 on 2024-12-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0001_initial"),
        ("tv", "0004_alter_tvepisode_remote_server_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvepisode",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Date modified"),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="release_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Release name"
            ),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="remote_server_id",
            field=models.CharField(max_length=255, verbose_name="ID on remote server"),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="remote_server_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL on remote server"
            ),
        ),
        migrations.AlterField(
            model_name="tvepisode",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("u", "Upcoming"),
                    ("s", "Searching"),
                    ("d", "Downloading"),
                    ("f", "Finished"),
                    ("a", "Archived"),
                    ("i", "Ignored"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Date modified"),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="release_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Release name"
            ),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="remote_server_id",
            field=models.CharField(max_length=255, verbose_name="ID on remote server"),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="remote_server_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL on remote server"
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date added"),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Date modified"),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="episode_fallback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episode_fallback",
                to="artwork.artwork",
                verbose_name="Episode Fallback Art",
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="image_show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_show",
                to="artwork.artwork",
                verbose_name="Show Poster",
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="release_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Release name"
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="remote_server_id",
            field=models.CharField(max_length=255, verbose_name="ID on remote server"),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="remote_server_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL on remote server"
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="season_fallback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_fallback",
                to="artwork.artwork",
                verbose_name="Season Fallback Art",
            ),
        ),
    ]
