# Generated by Django 5.1.4 on 2025-01-13 16:19

from django.db import migrations, models


def migrate_foreign_key_to_many_to_many(apps, schema_editor):
    Torrent = apps.get_model("autot", "Torrent")
    TVEpisode = apps.get_model("tv", "TVEpisode")

    # Transfer data from ForeignKey to ManyToManyField
    for torrent in Torrent.objects.filter(torrent_type__in=["e", "s"]):
        if torrent.torrent_episode.exists():
            episode = TVEpisode.objects.get(id=torrent.torrent_episode.first().id)
            episode.torrents.add(torrent)


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0009_alter_torrent_torrent_type"),
        ("tv", "0005_alter_tvepisode_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="torrents",
            field=models.ManyToManyField(related_name="torrent_tv", to="autot.torrent"),
        ),
        migrations.RunPython(migrate_foreign_key_to_many_to_many),
        migrations.RemoveField(
            model_name="tvepisode",
            name="torrent",
        ),
        migrations.RenameField(
            model_name="tvepisode",
            old_name="torrents",
            new_name="torrent",
        ),
    ]
