# Generated by Django 5.2 on 2025-05-17 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artwork", "0001_initial"),
        ("tv", "0006_tvepisode_torrents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvepisode",
            name="image_episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_episode",
                to="artwork.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="tvseason",
            name="image_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_season",
                to="artwork.artwork",
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="episode_fallback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="episode_fallback",
                to="artwork.artwork",
                verbose_name="Episode Fallback Art",
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="image_show",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_show",
                to="artwork.artwork",
                verbose_name="Show Poster",
            ),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="season_fallback",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="season_fallback",
                to="artwork.artwork",
                verbose_name="Season Fallback Art",
            ),
        ),
    ]
