# Generated by Django 5.2.2 on 2025-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0008_alter_tvepisode_image_episode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="runtime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
