# Generated by Django 5.2.3 on 2025-06-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0009_tvepisode_runtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tvepisode",
            old_name="remote_server_id",
            new_name="tvmaze_id",
        ),
        migrations.RenameField(
            model_name="tvseason",
            old_name="remote_server_id",
            new_name="tvmaze_id",
        ),
        migrations.RenameField(
            model_name="tvshow",
            old_name="remote_server_id",
            new_name="tvmaze_id",
        ),
    ]
