# Generated by Django 5.2.6 on 2025-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0010_rename_remote_server_id_tvepisode_tvmaze_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="imdb_id",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name=255
            ),
        ),
    ]
