# Generated by Django 5.2.6 on 2025-10-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("tv", "0011_tvshow_imdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="credit",
            field=models.ManyToManyField(to="people.credit"),
        ),
    ]
