# Generated by Django 5.2.6 on 2025-10-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0012_tvshow_credit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvshow",
            options={"verbose_name": "TV Show", "verbose_name_plural": "TV Shows"},
        ),
    ]
