# Generated by Django 5.2.8 on 2025-12-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autot", "0027_alter_appconfig_file_archive_operation"),
        ("tv", "0013_alter_tvshow_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="target_bitrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="autot.targetbitrate",
            ),
        ),
        migrations.AddField(
            model_name="tvseason",
            name="target_bitrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="autot.targetbitrate",
            ),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="target_bitrate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="autot.targetbitrate",
            ),
        ),
    ]
