# Generated by Django 6.0.1 on 2026-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0014_tvepisode_target_bitrate_tvseason_target_bitrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvepisode",
            name="number_offset_overwrite",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
